[project]
name = "MojoX"
version = "0.1.0"
description = "Real-Time Video Object Detection with Mojo Kernels and MAX Graph"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
run = "python src/app.py"
benchmark = "python benchmark/benchmark_mojo.py"
benchmark-python = "python benchmark/benchmark_python.py"
demo = "python src/app.py --demo"
create-sample = "python demos/create_sample.py"

[dependencies]
python = ">=3.10,<3.12"
numpy = ">=1.24,<2.0"
pillow = ">=8.0"
ffmpeg = ">=6.0"
opencv = ">=4.8"
pip = "*"

[pypi-dependencies]
# CUDA-enabled PyTorch
torch = ">=2.0"
torchvision = ">=0.15"
# Other packages
ultralytics = ">=8.0"
opencv-python = ">=4.8"
pyyaml = ">=6.0"
tqdm = ">=4.64"
psutil = ">=5.9"
ffmpeg-python = ">=0.2.0"

[activation]
scripts = ["scripts/setup_mojo.sh"]
